services:
  concert-calendar:
    build: .
    container_name: concert-calendar
    ports:
      - "3001:3000"
    # env_file:
    #   - .env.local
    #   - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - concert_net

networks:
  concert_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.0.0/16
